### ISSUE TITLE
Replace time.Sleep() in test suite

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/gitops-operator#130]
### Is your task related to a problem? Please describe.

Currently test suite contains `time.Sleep()` which is not a optimize solution to wait for a status. 

### Describe the solution you'd like

Replace `time.Sleep()` with some kind of polling logic.

### Additional context

https://github.com/redhat-developer/gitops-operator/blob/b34fd46d1f3d2bf6dcaed2d0d072fa4ad0507298/test/e2e/gitops_service_test.go#L158

**Comment by jgwest** [comment]
This is a good pattern to use for this: https://github.com/argoproj-labs/applicationset/blob/2c62537a8e5a3d5aecad87b843870789b74bdf89/test/e2e/fixture/applicationsets/consequences.go#L24

Basically it's:
- Pass a function into Expect that returns `true` if the test condition has passed, `false` otherwise
- In Expect, keep calling the function until it returns true.
- If it DOESN'T return true in X minutes (for example, 3 minutes), then fail the test.

Then, you can replace your sleep calls with tests for the particular cluster resource state that you are waiting for (with a timeout for if it never succeeds).

**Comment by iam-veeramalla** [comment]
Hi @amitkrout , 

 You can use the `wait` package of kubernetes API Machinery. 
 [https://pkg.go.dev/k8s.io/apimachinery/pkg/util/wait](https://pkg.go.dev/k8s.io/apimachinery/pkg/util/wait)

**Comment by iam-veeramalla** [comment]
We still have some entries of time.sleep() in the operator e2e ginkgo tests. This can be addressed and replaced with the `wait` package as mentioned in my previous comment. 

However, we are no longer maintaining these tests. We have already migrated to kUTTL tests which will be integrated with the CI asap.
cc: @varshab1210 , let me know if you need any help in hooking the kUTTL tests to our CI.

**Comment by iam-veeramalla** [comment]
@wtam2018 @varshab1210 I have added `wontfix` label to this issue as we are interested in kUTTL tests going ahead.
