### ISSUE TITLE
ArgoCD CRD should support extraArgs such as kubectl-parallelism-limit

### ISSUE THREAD

**Issue by tux-o-matic** [redhat-developer/gitops-operator#211]
**Is your feature request related to a problem? Please describe.**
Command line arguments for the various ArgoCD component can not be set when using this Operator.

**Describe the solution you'd like**
Have the Operator support an *extraArgs* list under the *controller* section of the ArgoCD CRD and pass those as command line arguments to the ArgoCD application controller.

**Additional context**
This is a problem for reducing the default application controller `kubectl-parallelism-limit` value which can cause OoM errors when the controller Pod starts even with several GB of memory allocated.

**Comment by jannfis** [comment]
Hey, this change has been included in the argocd-operator a while ago: https://github.com/argoproj-labs/argocd-operator/pull/401. This will be included in the upcoming 1.2.1 release of gitops-operator.

For GitOps Operator release v1.3, which will be based on Argo CD v2.1.z, this setting will not be required anymore because the underlying bug has been fixed properly in Argo CD.

**Comment by jannfis** [comment]
`extraArgs` is probably useful anyway :+1:

**Comment by tux-o-matic** [comment]
Sounds great @jannfis , thanks.
Do you have a link to the bug solution you mentioned?

**Comment by jannfis** [comment]
The bug was fixed in `gitops-engine`: https://github.com/argoproj/gitops-engine/pull/281

**Comment by iam-veeramalla** [comment]
The bug is fixed in latest. Please feel free to re-open incase you notice any issues.
