### ISSUE TITLE
`argocd --core app sync` no longer working

### ISSUE THREAD

**Issue by domharries** [redhat-developer/gitops-operator#296]
**Describe the bug**

When our deployment pipeline talks to argo, it uses the `argocd --core` functionality to proxy through the openshift apiserver. But this now results in the following error:

```console
$ argocd --core app sync APP_NAME
FATA[0001] rpc error: code = FailedPrecondition desc = cannot find pod with selector: [app.kubernetes.io/name=argocd-repo-server]
```

Our repo server does not have that label:

```console
$ oc label --list pod/openshift-gitops-repo-server-7f6f9769d9-bnz6b
app.kubernetes.io/name=openshift-gitops-repo-server
image.upgraded=03242022-221222-UTC
pod-template-hash=7f6f9769d9
```

**To Reproduce**
1. Run `oc login` with a user who can access the `openshift-gitops` namespace
2. Run `oc project openshift-gitops` to set that as current namespace
3. Run `argocd --core app sync APP_NAME`

Note that some other commands such as `argocd --core app list`, `argocd --core app wait APP_NAME` work fine. Running `argocd app sync APP_NAME` also works (but that's not easy for us to do due to firewall & authentication issues).

**Expected behavior**
App syncs successfully

**Additional context**
- argocd client version: 2.3.2
- openshift-gitops version: 2.2.8

**Comment by jannfis** [comment]
Hi @domharries, the title of your issue states "no longer working", but I believe this has never worked before with OpenShift GitOps. 

Apparently, core's `sync` command selects the repository server to talk to using a hard-coded label, but OpenShift GitOps ever since named the Argo CD workloads differently (using the name of the operand as a prefix, instead of `argocd`).

I believe this change could be made to the CLI, so that it supports setting the repository server to talk to dynamically. However, as we don't officially support the CLI yet, I feel this would require a community contribution to upstream. You could also file an RFE via OpenShift support.

**Comment by domharries** [comment]
Hi @jannfis, I dug into this a bit more and it looks like the problem was actually introduced in argocd CLI v2.3.x, if I run with v2.2.8 the sync works fine. I'm not sure whether that changes anything - happy to open an issue in https://github.com/argoproj/argo-cd if that's appropriate.

**Comment by iam-veeramalla** [comment]
Hi @domharries , Please open issue with argocd-cli. Thanks :)

**Comment by Diliz** [comment]
Hello!

Can you reopen this issue?

I opened an issue on argocd side (https://github.com/argoproj/argo-cd/issues/10200), but you could have provided a way to just play with the pod selectors here (like a prefix to set or else), even if it's hard coded on their side, at least we could have matched their selector, it's not an issue with argocd default installation but with openshift gitops, since it's the "openshift-gitops" naming that breaks the whole argocd cli things in the first place.

At least you should have created this issue yourself @iam-veeramalla instead of closing it wildly, there's issues with using argo only with kubernetes plain yamls instead of its apis.
